@echo off
echo 正在清理tools目录中的无关文件...
del blog_editor_new.html
del final_editor.html
del fixed_editor.html
del simple_blog_editor.html
del working_blog_editor.html
del working_editor.html
del open_blog_editor_new.bat
del open_final_editor.bat
del open_fixed_editor.bat
del open_simple_editor.bat
del open_working_editor.bat
del image_helper.bat
del image_helper.rb
del image_preview.html
del image_references.md
del open_image_preview.bat
del test.sh
echo 清理完成！只保留了原始的blog_editor.html和open_blog_editor.bat文件。
pause
